# Generated by Django 6.1.1 on 2026-09-14 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_experience_thumbnail_experienceimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='started_at',
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(default='Active Member', max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='OrganizationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='organization_images/')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.organization')),
            ],
        ),
    ]
